---
title: "Previsão de gastos no nubank"
output: html_document
---

```{r include=FALSE}
caminho = "C:/Users/vinho/git/previsaoGastosNubank/"
setwd(caminho)
library(readr)
library(dplyr)
library(knitr)
library(lubridate)
<<<<<<< HEAD
require(randomForest) # Arvores de Decisão
library(caret)        # createDataPartition()
library(quantmod) # cotações das ações e do Ibov
library(Quandl) # Selic BACEN
#library("xlsx")
source("codigos/carregar_varios_arquivos_csv_simultaneamente.R")
=======
source(sprintf("%*scodigos/carregar_varios_arquivos_csv_simultaneamente.R",0,caminho))
>>>>>>> c3eb2c3180a10ccb062d844f2edfcf4463a83aa0
```

# Valores Positivos
```{r Mostrar Valores Positivos}
contasPositivas <- contasJohn %>% arrange(date) %>% filter(amount > 0)
#kable(contasPositivas)
```

# Valores Negativos
```{r Mostrar Valores Negativos}
#kable(contasJohn %>% arrange(date) %>% filter(amount <= 0))
```

# Agrupamento por dias/soma e média dos gastos
```{r Dias por soma e media}
# Verificar pq o trimestre não bate com as datas e depois agrupar por dias novamente, para enviar ao modelo
source(sprintf("%*scodigos/juntarDiasMesesTrimestresDeGastos.R",0,caminho))
DiariaMensalETrimestral
write.csv(DiariaMensalETrimestral, "Nubank.csv")
base = DiariaMensalETrimestral
```
# Aplicar modelo Random Forest com tecnicas
```{r}
source("modelos/modeloRandonForest.R")
rf_model_sales
```


# Normalizar as variaveis preditoras numericas
```{r Normalizar}
base = DiariaMensalETrimestral
cols <- c(names(base))
cols <- cols[-1]
cols <- cols[-1]
base$month = as.factor(base$month)
base$month = as.numeric(base$month)
base$year = as.factor(base$year)
base$year = as.numeric(base$year)
colunas <- cols
str(base)
base[, cols] <- scale(base[, cols])
base
```

# Aplicar modelo Random Forest com normalização
```{r}
source("modelos/modeloRandonForest.R")
rf_model_sales
```



